microsoft/opensource-management-portal

- app.js
- configuration.js
- data.js
- middleware/error-routes.js
- middleware/index.js
- middleware/passport-config.js
- middleware/passport-routes.js
- oss/index.js
- public/css/oss.css
- routes/index-authenticated.js
- routes/unlink.js
- views/creategithubaccount.jade
- views/layout.jade
- views/link.jade
- views/message.jade
- views/org/index.jade
- views/org/pending.jade
- views/org/profileReview.jade
- views/unlink.jade
- views/welcome.jade
_While comments are appreciated, this is a staged set of changes, so feedback will be addressed in a future set of commits_
This feature introduces the concept of a "primary authentication scheme" which is 
used for authentication of the site and the primary identity for the link; the "secondary" 
scheme is then used for authorization when linking and managing accounts.
A new configuration property, `PRIMARY_AUTHENTICATION_SCHEME`, is added, and at this time it supports "aad" or "github".
This is an initial commit which is part of a number of parallel changes happening to 
enable this, so even after this is merged in, it should not be considered a stable feature.
The default primary authentication is GitHub, to be compatible with the original design 
of this management portal.
The driving …
> Active Directory primary authentication support

- views/nav.pug
No longer duplicating username and displayName when present.
Since a GitHub session may not be present, and we do not typically
store the GitHub display name, it will fall back to username. No
need really for us to do that in the UI.
> User Tile: Improved UI

- middleware/passport-config.js
- package.json
Using v2.0.1. Using the single tenant (not common) endpoint based on the realm/tenant.
> Moving to the latest passport-azure-ad

- routes/api/createRepo.js
Similar to #30, working to protect large swaths of admin permission grants. This change actively downgrades 'admin' permissions to the broad/everyone teams to 'read' only.
A nice-to-have future improvement on this might be to add configuration to opt in or out of this feature if you have a scenario where you want such a large grant.
> Downgrading broad admin access in repo create API

- business/operations.js
- business/organization.js
- business/team.js
- jobs/firehose/task.js
- lib/github/core.js
- lib/github/restApi.js
- middleware/initialize.js
- webhooks/organizationProcessor.js
- webhooks/tasks/automaticTeams.js
This adds a feature to block large permission grants (write and/or admin) to teams that are "very large".
A common scenario we see:
- A user unfamiliar with the specifics of GitHub permissions creates a new repository; they receive administrative rights over their new repo
- The user wants to collaborate with others in the organization
- User goes to GitHub, collaborators tab for their repo, and adds a team such as "Everyone at Microsoft" to the repository
- User changes the permission level from "read" to "admin" [or write], not understanding the implications
- Over 7,000+ users are given administrative permission over the repo
- Over 7,000+ users get annoyed if they have 'automatically watch new repositories' configured in their GitHub notification settings
- Over 7,000+ users get …
> Large permission grant protections/blocks

- package.json
* Added `npm` script to lint
* Added `npm` script to fix lint
* Updated `npm test` to call the newly created `npm` script
* Bumped `eslint` to `4.0.0` since previous version was not catching lint.  Once merged there will be lint unless https://github.com/Microsoft/opensource-portal/pull/54 is merged first.
Sorry about all the PRs!
> Lint script

- config/continuousDeployment.js
- views/layout.pug
Adds the ability to show basic build info such as build, release, commit ID, _if_ that information is provided inside the `package.json` for the app. Otherwise, no-op.
> Layout, config: adding continuous deployment config

- business/organization.js
- routes/api/client/newOrgRepo.js
The original implementation for 1ES day was specifically targeted at
private only. This aligns with the configuration values in the orgs.
> New repo client API: allow public repositories

- package.json
Hi.  I realized that creating a lint script just to pass in an argument to an npm sciript probably isn't the right thing to do considering npm scripts support passing in arguments out of the box.
https://docs.npmjs.com/cli/run-script
In this case it would be:
`npm run lint -- --fix`
> NPM Script: Remove lint:fix

- business/organization.js
While always supported in code, the code to read configuration
only supported a single 'special team'. This allows arrays of
values.
> Special teams: allowing multiple configured teams

- README.md
- business/operations.ts
- business/organization.ts
- business/repository.ts
- config/features.json
- features/newRepositoryLockdown.ts
- routes/org/team/maintainers.ts
- routes/org/team/members.ts
- tsconfig.json
- views/email/newrepolockdown.pug
- webhooks/tasks/repository.ts
To work around persistent GitHub bugs we have had the past few years related
to setting the member privilege level for many of our organizations to not
allow members to create repos, we are exploring this new opt-in only feature
flag called "direct new repo lockdown" that will help us to try and experiment
a way to allow our members to directly create repos.
The current prototyping design of this feature is:
1. if a repo is created by a GitHub App (a bot) or an approved system operations account, or the existing new repo workflow, no-op
2. if a repo is created by a member of the GitHub org, the repo is "locked down" - removing their collaborator and team permissions - and they are sent an e-mail asking them to complete the new repo setup by entering into our existing internal wizard for …
> opt-in feature: repo lockdown

- middleware/initialize.ts
The conditional logic to determine wr port was overridden to 6380
`wr = {}`
> Object {  }
`wr.port = 6379`
> 6379
`wr.tls = undefined`
> undefined
`wr.port = wr.port || (wr.tls ? 6380 : 6379);`
> 6379
`wr.port = wr.port || wr.tls ? 6380 : 6379;`
> 6380
```
> Update witness port default

- Dockerfile
- package.json
> Add 'npm run-script build' mentioned in the README.md

- business/organization.ts
- routes/org/membership.ts
- views/org/publicMembershipStatus.pug
The publicize/conceal operation on a GitHub organization requires an
active GitHub user session including an enhanced write-scoped token.
In the original OAuth world, this required a new OAuth dance; however,
with a GitHub App, we just need the token available. Adding the existing
middleware to require an active GitHub session for the membership page
helps achieve this.
Kudos to @wbsmolen for the bug report in #123
> bugfix: membership publicize

- business/operations.ts
- config/mail.json
- features/newRepositoryLockdown.ts
- jobs/managers/task.ts
- lib/graphProvider/microsoftGraphProvider.ts
- lib/mailProvider/customMailService.ts
- lib/mailProvider/directoryMailService.ts
- lib/mailProvider/index.ts
- lib/mailProvider/mockMailService.ts
- lib/mailProvider/smtpMailService.ts
- middleware/initialize.ts
- middleware/staticClientApp.ts
- middleware/staticSiteAssets.ts
- pg.sql
- routes/api/client/newOrgRepo.ts
- routes/api/client/newRepo.ts
- routes/api/createRepo.ts
- routes/org/team/index.ts
- views/email/repoApprovals/autoCreated.pug
If a manager is known for an employee, we will also notify
the manager via a carbon copy on e-mails related to new repos,
locked forks, or newly created repos that still need classification.
As a quick change, this does not add a feature flag to enable or disable
this; however, if a manager is not known via the corporate contacts or
cached employee information system, there will be no error.
Also adds a new `directory mail provider` that integrates with a slightly
different email service we have been using. The new provider type name
is 'directory', but it is not standard in the app, just opt-in.
> New repo emails: notify the manager

- business/operations.ts
- business/organization.ts
- business/team.ts
- config/features.json
- config/github.teams.json
- features/teamMemberToMaintainerUpgrade.ts
- jobs/reports/organizations.ts
- routes/org/2fa.ts
- routes/org/team/index.ts
- routes/org/team/maintainers.ts
- routes/org/teams.ts
- transitional.ts
- views/email/teamMemberSelfServiceMaintainerUpgrade.pug
- views/org/team/index.pug
- webhooks/tasks/team.ts
This introduces a new opt-in (feature flag) capability to reduce the
amount of manual organization operations that are required for
common scenarios.
For a relatively small GitHub team size (configurable, default to
around 15 people), this allows people to self-service "upgrade"
themselves to be a team maintainer if the team does not have
many maintainers.
The # of maintainers that are supported by default for this feature
to light up is zero (0) or 1... since we recommend that every
team have at least 2 maintainers.
When a user upgrades themselves, this also contacts the other linked
maintainers (if there already is at least one), or the other members of the 
team (if there are no maintainers) so that there is awareness and
visibility of the change.
> New feature: self-service team maintainer upgrade

- middleware/errorHandler.ts
- middleware/links/index.ts
- middleware/passport-routes.ts
- package-lock.json
- package.json
- routes/index-authenticated.ts
- routes/index-linked.ts
- routes/index.ts
- routes/link-cleanup.ts
- routes/link.ts
- routes/teamsPager.ts
- routes/unlink.ts
- transitional.ts
- views/error.pug
- views/index.pug
- views/link.pug
- views/org/pending.pug
- views/org/profileReview.pug
- views/org/publicMembershipStatus.pug
- views/teams/index.pug
To help address user confusion.
- Allows people to unlink themselves in the "security mismatch" scenario which used to take bothering us for manual ops
- Cleans up the first-time user experience to clearly remind them to join a GitHub org (i.e. "you aren't done yet!")
- Cleans up the first-time experience when you land on the Teams view with instructions pointing you at the GitHub Help page for GitHub Teams, and then telling you you likely do not need to do anything. Includes a button to go to the org main page as well.
> Improved link/join experience

- routes/org/repos.ts
- views/includes/corporateRepoMetadata.pug
- views/repos/defaultBranch.pug
- views/repos/pills.pug
- views/repos/repo.pug
Creates a new temporary, dedicated tab for renaming the default
branch.
Encourages rename if the old default is present, otherwise it is
not emphasized.
Points to guidance.
> Relocates the rename default branch experience (fixes #153)

- .gitignore
- middleware/corporateViews.ts
This is to fix an error if you have not created a `views/corporate/` folder:
```
Error: ENOENT: no such file or directory, scandir '/working/directory/opensource-portal/views/corporate'
```
> Fix missing corporate views

- lib/caching/redis.ts
- lib/github/core.ts
Wrong method called getObject instead of getCompressed.
When cache is stored as compressed object, it is gzipped however the getObject returns gzipped object before extracting, the JSON.Parse fails.
> The postgres compress object returned gibberish

- views/reposToolbar.pug
This PR ensure that the link to the FOSS Fund on the starting page is only shown when the `config.features.allowFossFundElections` is enabled. 
However I'm not sure if that is the proper feature flag for that or if it makes sense to add some additional configuration.
> feature flag the link to the FOSS Fund

- views/teams/index.pug
This PR resolves an issue where the teams view throws an error due to inconsistent indention with indenting the `if onboarding` with 4 spaces. 
```
portal_1        | GET /ospo-testing-org/teams?joining=ospo-testing-org 302 1.602 ms - 90 plain dbdbc016-0e25-4cf7-80f9-8e4d6260aca6
portal_1        | Error: /usr/src/repos/views/teams/index.pug:38:1
portal_1        |     36|           a.btn.btn-default.btn-sm(href=organization.baseUrl) Go to the main #{organization.name} page
portal_1        |     37|
portal_1        |   > 38|     .row
portal_1        | --------^
portal_1        |     39|       .col-md-8
portal_1        |     40|         form.form-horizontal#entitySearch(style='margin-top:24px')
portal_1        |     41|           .form-group
portal_1        |
portal_1        | Inconsistent …
```
> Fix inconsistent indentation and remove trailing whitespace

- config/github.links.postgres.json
This PR sets a default for the `config.github.links.postgres.tableName` to the reasonable value `links`. This is the same tablename, which is created via `pg.sql` and therefore makes it easier to setup without needing to fiddle too much with the settings. 
https://github.com/microsoft/opensource-portal/blob/a17d48e8efd1a4b299363acb3049eee1f5983487/pg.sql#L148-L163
> make the links table the default table for storing links

- Dockerfile
This PR updates the Dockerfile to use the same node base image for built and run stage. 
For this an Dockerfile `ARG` is defined and used in both places to ensure that when updating the image it is consistent for both stages.
> use same docker image for build and run stage

- config/microsoftOpenSource.json
- views/nav2.pug
This PR allows that the link behind "Use" and "Release" on the header of the portal can be configured with a custom link. 
This is especially helpful if resources for use/release of open source is not located at `config.microsoftOpenSource.explore + 'release'`, but in other places (e.g. dedicated wiki pages). 
If the configuration is not set it will default to the current behavior.
> make use and release link configurable

- docker-compose.yml
- middleware/initialize.ts
- transitional.ts
This PR implements that when `config.redis.key` is not set authentication to the redis cache isn't tried (and fails).
Additionally it adds to the `docker-compose.yml` that the redis should start in unprotected mode to allow unauthenticated connections. 
Alternatively we could as well set a default key in both the redis configuration and the docker compose via `redis-server --requirepass yourpassword`
> make redis auth optional and disable protected mode for docker redis

- business/operations.ts
This PR makes the usage of the GraphProvider optional and uses the `config.graph.require` variable to determine if corporateValidation should be used and if an error should be thrown if a graph provider is not configured. 
Similiar to how already the check in the initialize phase is done: https://github.com/microsoft/opensource-portal/blob/ead2c878142f9e30ca077df4d8765db43b2d4cd5/middleware/initialize.ts#L412-L414
> use config.graph.require to disable graph provider check and corporateValidation

- views/nav2.pug
This PR removes the explicit color from the Portal name as with the default asset pack it would be the same as the background of the header: 
After removing the the explicit color (aka what this PR does): 
---
⚠️ Depending on what color scheme the Microsoft internal version uses, this may cause problems.
For this the color could be added in the css as important (as otherwise the bootstrap default of `#fff` will be used) file of the microsoft asset pack like this:
```css
.navbar-brand {
color: #333 !important;
}
```
> Remove explicit color from companyPortalName

- views/people/index.pug
- views/repos/index.pug
- views/teams/index.pug
This PR fixes a small visible bug in the UI, where the "next ->" & "<- previous" link on the repo, people and team pager are not correctly intended and thus the link is not behind the text.
Additionally I remove the if statement and just relay on hiding the element with the CSS class and that works great and reduces the complexity a bit.
Lastly it as well removes the special logic to switch between displaying `One member` if only a single member is returned and just use the default template (`1 - 1 of 1 members`)
<details>
<summary>Visualized rendered output before</summary>
```html
<ul class="pager">
<li class="previous">
<a href="?page_number=2&amp;sort=Alphabet"></a>
<span aria-hidden="true">← Previous</span> 
</li>
<li>67 - 99 of 36,842 members</li>
<li class="next">
<a …
```
> fix previous/next links to be correctly enabled

- business/organization.ts
- config/features.json
- config/github.debug.json
- config/sudo.json
- features/README.md
- features/index.ts
- features/newRepositoryLockdown.ts
- features/sudo/index.ts
- features/sudo/noop.ts
- features/sudo/securityGroup.ts
- features/sudo/sudo.md
- features/sudo/teams.ts
- interfaces/companySpecificLightup.ts
- lib/graphProvider/index.ts
- lib/graphProvider/microsoftGraphProvider.ts
- middleware/github/orgPermissions.ts
- middleware/github/repoPermissions.ts
- middleware/github/teamPermissions.ts
- routes/settings/approvals.ts
Adds support for organization sudo privileges to flow from
security groups instead of from GitHub Teams as the source of
truth.
Sudo remains on by default and configured for teams.
Also provides for company-specific overrides if you have a
different system for authorization decisions that is not part
of the default kit.
> Organization sudo security group support

- routes/orgAdmin.ts
- views/organization/whois/linkEditor.pug
- views/organization/whois/result.pug
This PR allows portal sudoers to manually create links for users. Allowing admins to manually link e.g. service users and users, which are not able to use the portal (e.g. externals). 
For this the linkEditor is enhanced to either load the link information, if existing (current behavior) or if not existing pre-fill the fields with the GitHub user information.
Fixes #189
> allow manual linking of users by admins

- business/operations.ts
- config/features.json
- config/github.debug.json
- config/sudo.json
- features/sudo/index.ts
- features/sudo/portal.ts
- features/sudo/sudo.md
- interfaces/companySpecificLightup.ts
- user/index.ts
Supports using security groups for portal sudo permissions
instead of the primary GitHub org's sudo configuration, if
present.
Breaking feature change:
This feature is not enabled by default and must use a feature flag
to opt-in.
The feature flag is "FEATURE_FLAG_ALLOW_PORTAL_SUDO".
The standard behavior, when the flag is enabled, is still to use
the first org. Alternatively, configuration and a SG ID can be provided.
> Portal sudo SG support

- routes/orgAdmin.ts
I tested today the feature flag for the `allowAdministratorManualLinking` and noticed that it skips the `operations` attribute when trying to access the config. 
This PR updates that accesses the configuration of the operations attribute. As we need the `operations` later in the method anyway it will be only once defined and then reused. 
Part of #189
> use config from inside operations for determing allowAdministratorManualLinking

- routes/peopleSearch.ts
- views/people/index.pug
This PR allows to specify an additional query parameter in the people search, this is especially handy when working with large organizations and teams to get see everyone on a single page. 
The PR only exposes it as a query parameter and doesn't provide a UI element for picking the page size, mainly to allow only power users to leverage it (e.g. to send mails to everyone on the page and with a large pageSize this is easier than copying several pages together).
> allow custom pageSize for people search

- README.md
@jeffwilcox moved his blog some time ago. Updating the link to the introduction to the correct URL: https://jeffwilcox.blog/2015/11/azure-on-github/
> Fixed link to Jeff Wilcox's blog

- api/createRepo.ts
- business/operations/index.ts
- config/brand.json
- jobs/reports/mailer.ts
- lib/emailRender.ts
- lib/mailProvider/index.ts
- lib/mailProvider/smtpMailService.ts
- routes/org/team/approval/index.ts
- views/email/footer.pug
- views/email/header.pug
- views/email/newrepolockdown.pug
- views/email/newrepolockremoved.pug
- webhooks/tasks/automaticTeams.ts
* Fix SmtpMailService config
* Introduce new variable for company logo source
* Pass config to RenderHtmlMail calls to access variables inside pug templates
* Replace some occuences of hardcoded Microsoft strings for config variables
> Remove hardcoded references to microsoft from mail templates

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/container.yml
Could split these out separately, but figured their semi-related:
- unpin the actions versions, so there is less Dependabot noise, except for a new major version
- Remove a strategy key, that only applies when a `matrix` value is used
- Update a the container job, since it was only running for a non-existant develop branch
> ci: Update versions and targets

- .github/workflows/ci.yml
Probably won't make a major differene to the build time, but doesn't hurt
> ci: use built-in NPM cache with setup-node

- .eslintignore
- .eslintrc.js
- package.json
Moved the ignores to the separate file, so they should be easier for IDEs to pick up at the same time.
> chore: use lint-staged for ESLint

- .eslintrc.js
- config/corporate.trainingResources.js
- config/github.templates.js
- views/js/search.js
Mostly were for environment variables that weren't automatically exposed, but a few were referencing things that didn't exist in scope
> fix: ESLint no-undef

- default-assets-package/resources/repos-css/oss.css
- default-assets-package/resources/scss/_build.scss
- views/email/email.css
Added packages
```
"stylelint": "^14.13.0",
"stylelint-config-standard": "^28.0.0",
"stylelint-config-standard-scss": "^5.0.0",
```
and config
```
{
"extends": [
"stylelint-config-standard",
"stylelint-config-standard-scss"
],
"rules": {
"no-descending-specificity": null
}
}
```
while ignoreing `public/` and `node_modeles/`.
Since there isn't much going on for styles I didn't think it made sense to wire it it right now, rather than a one-off pass
> fix: Run Stylelint on CSS/SCSS

- .eslintrc.js
- lib/entityMetadataProvider/table.ts
Doesn't seem like it was a null assertion, rather than a misplaced `!`
> fix: @typescript-eslint/no-non-null-assertion

- .eslintrc.js
- business/team.ts
- entities/teamJoinApproval/teamJoinApproval.ts
- lib/caching/blob.ts
- lib/caching/cosmosdb.ts
- lib/github/composite.ts
- lib/github/restApi.ts
- lib/linkProviders/postgres/postgresLinkProvider.ts
Some characters don't need to be escaped anymore inside the string templates, and regex characters don't need escaping inside the `[]` ranges
> fix: no-useless-escape

- .github/workflows/ci.yml
- .markdownlint-cli2.jsonc
- .vscode/settings.json
- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/api.md
- docs/changelog.md
- docs/configuration.md
- docs/data.md
- docs/decisions/2013-02-portal.md
- docs/decisions/2013-03-eventual-consistency.md
- docs/decisions/2016-08-js.md
- docs/decisions/2017-06-postgres.md
- docs/decisions/2019-08-client-apis.md
- docs/features.md
- docs/githubApp.md
- docs/jobs.md
- docs/metrics.md
- docs/scripts.md
- docs/staticSiteAssets.md
- features/sudo/sudo.md
- package-lock.json
- package.json
- Create the config file using CLI2, since that is the same as the VSCode extension now
- Add to CI and Lint Staged
- Cleanup all but a minimal set of rules
- Disable some .vscode settings, since the formatting seemed to fight it a bit
- Made some best-guesses at the re-leveling of some headings, where there were multiple H1s
Didn't add the `.vscode/extensions.json` to suggest the plug-in, or add a problem-matcher for the CI runs to add annotations to the Files view
> chore: Integrate Markdownlint

- .eslintrc.js
- jobs/firehose/task.ts
I think the one usage is probably intented, but the inline disable probably makes more sense
> chore: enable no-constant-condition

- routes/teamsPager.ts
Conditional logic in the teamPager route only renders teams if the user is a `member` of at least one team.  If a user is a `maintainer` of all of their teams and never a `member` no teams display when selecting "Your Teams."
> Fix bug in the teamPager.

- views/index.pug
This PR enables users to also see locked orgs as well, but visualizes them differently than open orgs.
> Update index page to include locked orgs.

- user/aggregate.ts
- views/index.pug
```sql
-- confirm only admin roles exist
select count(*), metadata->>'role' from organizationmembercache group by metadata->>'role'; ;
```
|count|role|
|-|-|
|4|admin|
Before this commit, orgs that a user is an admin of show up in the “available organizations” area.
After this commit, those orgs show up as orgs the uers is a member of.
> **Note**:
>  I have not performed an exhaustive analysis to see if the new `in` logic should be used in any other views.
> Fix bug not showing orgs the user is an admin of.  Fixes #491.

- middleware/initialize.ts
Without this, start-up fails in a local dev environment when using the base Redis container and no auth.
```
TypeError: Invalid argument type
at encodeCommand (/Users/garnertb/projects/github-portal/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
at RedisCommandsQueue.getCommandToSend (/Users/garnertb/projects/github-portal/node_modules/@redis/client/dist/lib/client/commands-queue.js:138:45)
at Commander._RedisClient_tick (/Users/garnertb/projects/github-portal/node_modules/@redis/client/dist/lib/client/index.js:507:76)
at Commander._RedisClient_sendCommand (/Users/garnertb/projects/github-portal/node_modules/@redis/client/dist/lib/client/index.js:494:82)
at Commander.commandsExecutor (/Users/garnertb/projects/github-portal/node_modules/@redis/client/dist/lib/client/inde …
```
> Ensure the redis key is set before attempting to auth with it.
