- README.md
- package.json
- increments `package.json` to v4-alpha.0 [pre-release version per SemVer]
- adds a minor warning that there will be breaking changes here
> Initial v4-alpha warning and version update

- middleware/hsts.js
- middleware/index.js
- package.json
> Adding HSTS middleware

- .gitignore
- oss/index.js
- routes/org/team/index-maintainer.js
This evens out differences between the public `master` and an internal fork that had diverged slightly.
> Minor portal merges

- package.json
This is a minor update to address outdated NPM modules.
- adal-node: recent minor fixes, verified no regressions
- mocha: moving to v3, verified tests all still pass and execute fine
> Updated NPM Packages

- README.md
- lib/context.js
- lib/insights.js
- lib/user.js
- middleware/appInsights.js
- middleware/index.js
- routes/index-authenticated.js
- routes/link-cleanup.js
- routes/link.js
- routes/unlink.js
- test/context.js
This change is the early stage work to enable the user of AppInsights 
within the application, both for library functions as well as the request 
pipeline.
- Adds a new `lib/insights.js` file that adds common properties into an existing client object OR simply provides a mock-style interface with a debug provider for local test scenarios
- Moves the correlation ID assignment earlier in the middleware pipeline
- Integrates the correlation ID into event properties automatically
- Creates a wrapped/mock client with each request to pass throughout the application
- Updates the README to include the events that are being added
- Updates `lib/context.js` to use some initial ES6 goodness (`const`, `let`)
- Adds a few tests
> Application Insights client

- routes/api/client/newOrgRepo.js
broad teams should also appear within the larger
team list of "other teams"
> Client API: broad teams fix

- business/operations.js
- business/organizationMember.js
- middleware/initialize.js
- views/email/largeTeamProtected.pug
- webhooks/tasks/automaticTeams.js
Notifies the initiator of the permission change when their change is protected and reverted.
> Large team protection: mail notification

- config/github.organizations.js
- package.json
Optionally supporting the org config through an environment
module.
> Supporting GitHub organizations from the environment

- business/operations.js
- config/github.links.events.json
- lib/context.js
- lib/user.js
- package.json
- routes/api/apiUserContext.js
- routes/api/client/newOrgRepo.js
- routes/api/index.js
- routes/index-authenticated.js
- routes/link-cleanup.js
- routes/link.js
Adds the ability to call webhook-style HTTPS endpoint(s) with link and unlink events.
> Exposing link/unlink events

- app.js
- middleware/appInsights.js
- middleware/errorHandler.js
- middleware/github/orgPermissions.js
- middleware/index.js
- middleware/initialize.js
- middleware/links/usernameConsistency.js
- middleware/passport-config.js
- middleware/session.js
- Adds docker and kubernetes deployment support
- Proper logic for container deployments with SSL termination
- Adds optional analytics reporting for Google Analytics campaigns
- Minor bugfixes in middleware routes
> Recent Middleware updates

- routes/api/createRepo.js
This is the first pull request toward making this code base run in docker.  This is a simple one that fixes the case of the file name so the require statement will load the file on a linux file system where names are case sensitive.
> Fixed case of filename to work on linux file systems

- config/activeDirectory.json
- config/containers.json
- config/github.debug.json
- config/github.systemAccounts.json
- config/microsoftOpenSource.json
- config/witness.approval.json
Not committing yet (have not tested) but wanted to have available for @RobCannon
> Adding missing config files

- Gruntfile.js
- package-lock.json
- package.json
- views/head.pug
- views/index.pug
- views/org/index.pug
- views/org/teams.pug
- views/thanks.pug
This library is no longer as necessary now that repo, team, and other
views have a proper search experience within the app. Simplifies
dependencies, and the underlying component was no longer maintained.
> Removes jquery-uitablefilter

- default-assets-package/resources/repos-css/oss.css
- routes/reposPager.ts
- views/email/footer.pug
- views/email/link.pug
- views/nav2.pug
- views/people/index.pug
- views/repos/index.pug
- views/teams/index.pug
This are some basic changes. Generalized company names, fixed text color to no longer be the same as the background and navigation buttons no longer show up when it is the last/first page anyways.
> UI adjustments and fixes

- routes/org/team/index.ts
- routes/org/team/leave.ts
- views/org/team/index.pug
this pull request adds the functionality to leave teams on your own.
> adding leave-team functionality

- Dockerfile
- package.json
Reverts microsoft/opensource-portal#106
> Revert "Add 'npm run-script build' mentioned in the README.md"

- Dockerfile
- package.json
Reverts microsoft/opensource-portal#109
> Revert "Revert "Add 'npm run-script build' mentioned in the README.md""

- README.md
- business/account.ts
- business/teamMember.ts
- business/user/context.ts
- config/webServer.json
- entities/teamJoinApproval/teamJoinApproval.ts
- lib/entityMetadataProvider/index.ts
- middleware/github/teamPermissions.ts
- middleware/initialize.ts
- package.json
- routes/org/membership.ts
- routes/org/profileReview.ts
- routes/org/team/delete.ts
- routes/org/team/maintainers.ts
- routes/org/team/members.ts
- routes/teamsPager.ts
- transitional.ts
- webhooks/tasks/membership.ts
- webhooks/tasks/organization.ts
- webhooks/tasks/repository.ts
This pull request fixes some bugs and adds documentation.
- overhauld documentation in the Readme.md
- fixed email and GitHub full name at ProfileReview-page
- enabled teams view on main page
- set default for config/webserver.json
- fixed postgres bug at team-approvals
- set default providername to "memory", so the memory provider is used when no provider is configured
- fixed database provider initialization and added fallbacks when Azure Table Storage is not configured
- redis authentication & port improvements
- added "build" command in the NPM scripts for compiling TypeScript
- fixed method calls for deleting teams and changing/refreshing maintainers since those methods return a Promise and don't use callbacks any more
- fixed bug at the teams view where an object got checked for …
> general bug fixes and improvements

- routes/contributions/index.ts
- views/contributions/index.pug
We had some users of the system receiving a message that they could
vote. Fixes that logic.
> The FOSS Fund vote button should only appear for eligible voters

- .vscode/launch.json
- README.md
- jobs/cleanupContributions/index.ts
- jobs/cleanupContributions/task.ts
- lib/linkProviders/index.ts
- lib/linkProviders/memory/memoryLinkProvider.ts
- lib/linkProviders/postgres/postgresLinkProvider.ts
- lib/linkProviders/table/tableLinkProvider.ts
- pg.sql
- scripts/migrateContributions/index.ts
The event entity, used for gathering contribution data, is being
normalized to use proper Postgres columns instead of the hacked-up
JSONB approach.
> Events: updating schema

- business/queryCache.ts
- entities/organizationMemberCache/organizationMemberCache.ts
- entities/organizationMemberCache/organizationMemberCacheProvider.ts
- entities/repositoryCache/repositoryCache.ts
- entities/repositoryCache/repositoryCacheProvider.ts
- entities/repositoryCollaboratorCache/repositoryCollaboratorCache.ts
- entities/repositoryCollaboratorCache/repositoryCollaboratorCacheProvider.ts
- entities/repositoryTeamCache/repositoryTeamCache.ts
- entities/repositoryTeamCache/repositoryTeamCacheProvider.ts
- entities/teamCache/index.ts
- entities/teamCache/teamCache.ts
- entities/teamCache/teamCacheProvider.ts
- entities/teamMemberCache/index.ts
- entities/teamMemberCache/teamMemberCache.ts
- entities/teamMemberCache/teamMemberCacheProvider.ts
- jobs/refreshQueryCache/task.ts
- lib/entityMetadataProvider/query.ts
- lib/mailProvider/directoryMailService.ts
- routes/administration/apps.ts
- user/aggregate.ts
- utils.ts
- views/administration/setup/apps.pug
- views/email/repoApprovals/autoCreated.pug
Cleans up the query cache for organizations that are no longer managed
by the app.
> Query cache: cleaning up deleted/unmanaged orgs

- lib/graphProvider/microsoftGraphProvider.ts
- routes/peopleSearch.ts
This fixes two small issues I ran into when setting up a local copy of this.
1. The `lowercaser` import in `peopleSearch` was causing troubles since it had the file extension included
2. An error message confused me for a good while since it was calling out the wrong configuration variable.
The rest of the changes in here are just beautification done by VSCode. 😄 
I am sure I will have more updates later as I adapt this to work for our purposes, but I wanted to introduce small batches to make them more digestible!
> Setup bugfixes

- .vscode/launch.json
- business/operations.ts
- business/repository.ts
- business/team.ts
- config/brand.json
- config/notifications.json
- entities/repositoryMetadata/repositoryMetadata.ts
- features/newRepositoryLockdown.ts
- jobs/firehose/task.ts
- lib/github/collections.ts
- package-lock.json
- package.json
- routes/api/createRepo.ts
- routes/undo.ts
- views/email/newRepoStale.pug
- Replaces extended operations mail with dedicated, optional notification email addresses for new repos, new links, and related operations
- Updates to newer libraries including Octokit v18
> Adding notification mails, Octokit update

- api/index.ts
- routes/index.ts
I was just working on another branch and noticed this breaking, related to the work merged earlier today.
> Update a couple of references to the new api code location

- api/client/newOrgRepo.ts
- api/index.ts
- api/people/link.ts
- api/publicRepos.ts
- middleware/passport-config.ts
- routes/contributions/index.ts
- routes/org/join.ts
- routes/org/newRepoSpa.ts
- routes/org/team/index.ts
- routes/peopleSearch.ts
- routes/reposPager.ts
There were a couple of things here:
1. I made a mistake in my previous PR, #147 and didn't update a couple of variable references
2. [The Express query type is no longer `any`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434), which required a bunch of explicit type assertions to be added. These should probably be updated later to have some stricter type checking, but this at least works for now.
I'm also being sure to remove the `'use strict';` statements when I see them.
After all this, the project builds and starts cleanly again!
> Fix build errors

- middleware/passport-config.ts
- middleware/passport-routes.ts
- middleware/passport/aadStrategy.ts
- middleware/passport/githubStrategy.ts
- routes/org/join.ts
- routes/org/repoWorkflowEngine.ts
- Removes old comments
- Updates a boolean from query string method
- New session regeneration code fix to preserve the referral URL
- Throws not implemented for the in-progress `oauth2` provider
- Refactors some default branch create code changes
> Integrating latest updates

- .eslintrc.js
- .github/workflows/ci.yml
- business/account.ts
- business/operations/index.ts
- business/organization.ts
- lib/github/collections.ts
- lib/github/core.ts
- lib/github/restApi.ts
- middleware/business/authentication.ts
- package-lock.json
- package.json
- routes/org/repoWorkflowEngine.ts
- scripts/postgres/setup.ts
- webhooks/tasks/organization.ts
- webhooks/tasks/repository.ts
Add ESLint and typescript setup, but disable all currently failing rules.
Touched a few files that had inline config already that meant the config suppression was overriden
> chore: Initial ESLint setup

- .eslintrc.js
- .github/workflows/ci.yml
- .prettierrc.json
- package-lock.json
- package.json
@jeffwilcox, this might be too early in your refactoring work to add, but you can always copy the `.eslintrc.js`, `.prettierrc.json`, and `package.json` changes when you ready, then run the `npm run fix` on you cleanup branch
> chore: Add ESLint Prettier config

- .eslintrc.js
- bin/www.ts
- business/account.ts
- business/repository.ts
- business/repositoryIssue.ts
- business/repositoryProject.ts
- business/repositoryPullRequest.ts
- business/teamMember.ts
- lib/caching/cosmosdb.ts
- lib/campaigns.ts
- lib/cosmosHelper.ts
- lib/entityMetadataProvider/table.ts
- lib/linkProviders/memory/memoryLink.ts
- lib/linkProviders/table/tableLink.ts
- lib/tableEntity.ts
- middleware/error-routes.ts
- middleware/errorHandler.ts
- middleware/onboarding.ts
- middleware/passport-routes.ts
- middleware/passport/githubRoutes.ts
- middleware/scrubbedUrl.ts
- routes/org/join.ts
- routes/org/team/approval/index.ts
- routes/thanks.ts
- utils.ts
Some of these were disabled to reduce the diff in the original PR and now pass. Few others had minimal instances now, so cleaned them in separate commits
> fix: cleanup more ESLint rules

- .eslintrc.js
- entities/organizationMemberCache/organizationMemberCache.ts
Not sure about the changed, but having both cases does appear to be incorrect, so I merge the query
> fix: no-duplicate-case

- docs/providers.md
- jobs/managers/task.ts
- lib/config/index.ts
- middleware/index.ts
- routes/administration/app.ts
- utils.ts
- views/nav2.pug
- views/org/publicMembershipStatus.pug
Was going to add cSpell, but decided to take another pass through first
> fix: various typos

- lib/github/restApi.ts
- middleware/business/authentication.ts
- routes/org/repoAdministrativeLock.ts
- scripts/localEnvironment.ts
- transitional.ts
- utils.ts
- webhooks/organizationProcessor.ts
Not sure the best tool to flag this, but these were flagged/unreferend looking in VScode. Maybe used on an internal fork though
> chore: remove unused code

- routes/org/join.ts
This bug in the join route causes a TypeError when campaignStateProvider is not set.
> Fix bug in organization join route.
